export const buzzwords = [
  'GraphQL - is an open-source data query and manipulation language for APIs and a query runtime engine.',
  'gRPC - is a modern open source high performance Remote Procedure Call (RPC) framework that can run in any environment.',
  'White-box testing - is a method of software testing that tests internal structures or workings of an application, as opposed to its functionality.',
  'Black-box testing - is a method of software testing that examines the functionality of an application without peering into its internal structures or workings.',
  'Shift-left testing - is an approach to software testing and system testing in which testing is performed earlier in the lifecycle.',
  'MQTT - (originally an initialism of MQ Telemetry Transport) is a lightweight, publish-subscribe, machine to machine network protocol for message queue/message queuing service.',
  'Low-hanging fruit - the obvious or easy things that can be most readily done or dealt with in achieving success or making progress toward an objective.',
  'MVP - Minimum viable product - is a version of a product with just enough features to be usable by early customers who can then provide feedback for future product development.',
  'Blob - Binary large object - is a collection of binary data stored as a single entity. Blobs are typically images, audio or other multimedia objects, though sometimes binary executable code is stored as a blob.',
  'JWT - JSON Web Token - is a proposed Internet standard for creating data with optional signature and/or optional encryption whose payload holds JSON that asserts some number of claims.',
  'Reverse-Proxy - is an application that sits in front of back-end applications and forwards client (e.g. browser) requests to those applications. Reverse proxies help increase scalability, performance, resilience and security. The resources returned to the client appear as if they originated from the web server itself.',
  'Proxy server - is a server application that acts as an intermediary between a client requesting a resource and the server providing that resource. It improves privacy, security, and performance in the process.',
  'Multitenancy - is a software architecture in which a single instance of software runs on a server and serves multiple tenants.',
  'HTML - Hypertext Markup Language - is the standard markup language for documents designed to be displayed in a web browser.',
  'YAGNI - You aren`t gonna need it - is a principle which arose from extreme programming (XP) that states a programmer should not add functionality until deemed necessary',
  'SOLID - is a mnemonic acronym for five design principles intended to make object-oriented designs more understandable, flexible, and maintainable.',
  'Pure function - is a function that has the following properties: 1. the function return values are identical for identical arguments (no variation with local static variables, non-local variables, mutable reference arguments or input streams), and 2. the function has no side effects (no mutation of local static variables, non-local variables, mutable reference arguments or input/output streams).',
  'Idempotence - a function is idempotent if multiple calls have the same effect on the system state as a single call, in other words if the function from the system state space to itself associated with the subroutine is idempotent in the mathematical sense given in the definition.',
  "DDD - Domain-driven design - is a major software design approach, focusing on modeling software to match a domain according to input from that domain's experts.",
  'Event sourcing - Event sourcing is an architectural pattern in which entities do not track their internal state by means of direct serialization or object-relational mapping, but by reading and committing events to an event store.',
  'CQRS - Command Query Responsibility Segregation - is a system architecture that extends the idea behind command–query separation to the level of services. Such a system will have separate interfaces to send queries and to send commands. As in CQS, fulfilling a query request will only retrieve data and will not modify the state of the system (with some exceptions like logging access), while fulfilling a command request will modify the state of the system.',
  'CAP theorem - states that any distributed data store can provide only two of the following three guarantees: 1. Consistency - Every read receives the most recent write or an error. 2. Availability - Every request receives a (non-error) response, without the guarantee that it contains the most recent write. 3. Partition tolerance - The system continues to operate despite an arbitrary number of messages being dropped (or delayed) by the network between nodes.',
  'REST - Representational state transfer - is a software design principle that was created as an outline to guide the development of the architecture for the World Wide Web.',
]
